core/urls.py
''' 
Module that provides all urls for core app.
'''

from django.urls import path
from core import views

app_name = 'core'
urlpatterns = [
    path('categories/', views.CategoryListView.as_view(), name='categoryList'),
    path('products/', views.ProductListView.as_view(), name='productList'),
    path('categories/<int:category_id>/',
         views.view_products_by_category, name='productsByCategoryView'),
    path('history/<int:product_id>/',
         views.view_price_history, name='priceHistory'),
    path('admin/db-download/', views.view_download_database,
         name="downloadDatabase"),
    path('admin/scrape', views.view_scrape_command, name="scrapeCommand"),
    path('admin/explore', views.view_explore_command, name="exploreCommand")
]

prihud/urls.py
import os
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('', views.Index, name='index'),
    path('login/', views.LoginView, name="login"),
    path('logout/', views.Logout, name="logout")
]

if (os.environ.get("ENV") == "dev"):
    urlpatterns += staticfiles_urlpatterns()

core/models.py
""" Module providing all models for the core app """

from django.utils.timezone import now
from django.db import models
from django.db.models import Min, Max
from django.utils.translation import gettext_lazy as _
from selenium.webdriver.common.by import By


class Statuses(models.TextChoices):
    """Choices for status field inside Target model"""

    SUCCESS = "S", _("Success")
    OUT_OF_STOCK = "O", _("Out of stock")
    NO_SELECTOR = "N", _("No selector set")
    PRICE_NOT_FOUND = "P", _("Price not found")
    CACHED = "C", _("Cached")
    UNDEFINED = "U", _("Undefined status")


class Frequencies(models.TextChoices):
    """Choices for frequency field inside Target model"""

    FOUR_TIMES = "F", _("Four times a day")
    TWO_TIMES = "T", _("Twice a day")
    DAILY = "D", _("Daily")
    WEEKLY = "W", _("Weekly")


class SelectorTypes(models.TextChoices):
    """Choices for custom_selector_type field inside Target model
    and selector_type field inside DefaultSelector model"""

    CSS = By.CSS_SELECTOR
    XPATH = By.XPATH
    TAG = By.TAG_NAME
    CLASS = By.CLASS_NAME


class Category(models.Model):
    """Category model"""

    name = models.CharField(max_length=128)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return self.name


class Product(models.Model):
    """Product model"""

    name = models.CharField(max_length=128)
    categories = models.ManyToManyField(Category)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return self.name

    def get_price_history(self):
        """Method for getting the price history of a product"""

        targets = Target.objects.filter(product_id=self.id).all()
        return (
            PriceHistory.objects.filter(target_id__in=[t.id for t in targets])
            .order_by("-created_at")
            .all()
        )

    def get_min_max_prices(self):
        """Method for getting the lowest and highest prices
        of a product's price history"""

        targets = Target.objects.filter(product_id=self.id).all()
        return PriceHistory.objects.filter(
            target_id__in=[t.id for t in targets]
        ).aggregate(Min("price"), Max("price"))

    def get_cheapest(self):
        """Get the cheapest price amongst all targets of a product"""

        targets = Target.objects.filter(product_id=self.id).all()
        return (
            PriceHistory.objects.filter(target_id__in=[t.id for t in targets])
            .annotate(Min("price"))
            .order_by("price")[0]
        )


class DefaultSelector(models.Model):
    """DefaultSelector model"""

    name = models.CharField(max_length=64)
    selector_type = models.CharField(max_length=16, choices=SelectorTypes.choices)
    selector = models.CharField(max_length=256)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return self.name


class Target(models.Model):
    """Target model"""

    alias = models.CharField(max_length=128, blank=True, null=True)
    url = models.CharField(max_length=256)
    selector = models.ForeignKey(
        DefaultSelector, on_delete=models.DO_NOTHING, blank=True, null=True
    )
    custom_selector_type = models.CharField(
        max_length=16, choices=SelectorTypes.choices, blank=True, null=True
    )
    custom_selector = models.CharField(max_length=256, blank=True, null=True)
    status = models.CharField(
        max_length=1,
        blank=True,
        null=True,
        choices=Statuses.choices,
        default=Statuses.SUCCESS,
    )
    frequency = models.CharField(
        max_length=1, choices=Frequencies.choices, default=Frequencies.DAILY
    )
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return self.alias or self.url

    def min_max_price(self):
        """Get the lowest and highest price of a target"""

        return PriceHistory.objects.filter(target_id=self.id).aggregate(
            Min("price"), Max("price")
        )

    def get_store_name_from_url(self):
        """Get store name from target url"""

        splitted = self.url.split(".")
        return splitted[1] if len(splitted) > 1 else ""

    def get_recent_price_history(self):
        """Get the most recent price history entry for a target"""

        return (
            PriceHistory.objects.filter(target_id=self.id)
            .order_by("-created_at")
            .first()
        )

    def is_available(self):
        """Check if a target is still available for purchase or not"""

        return self.status in [Statuses.SUCCESS, Statuses.CACHED]


class PriceHistory(models.Model):
    """PriceHistory model"""

    price = models.FloatField()
    target = models.ForeignKey(Target, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return f"{self.price} - {self.target} - {self.created_at}"


class Cookie(models.Model):
    """Cookie model"""

    url = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    value = models.TextField()
    path = models.CharField(max_length=256, null=True, default="/")
    domain = models.CharField(max_length=256)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return f"{self.url} - {self.name}"

    def get_all_grouped():  # pylint: disable=no-method-argument
        """Gets all cookies grouped by their url"""

        cookies = Cookie.objects.all()
        grouped = {}
        for cookie in cookies:
            if cookie.url not in grouped:
                grouped[cookie.url] = []
            grouped[cookie.url].append(cookie)
        return grouped

    def get_parsed(self):
        """Parses the cookie entry into a dict"""

        return {
            "name": self.name,
            "value": self.value,
            "path": self.path,
            "domain": self.domain,
        }

core/views.py
'''
Module providing all core app views.
'''
import os
import json
from datetime import datetime
import pandas as pd
from django.shortcuts import render
from django.views.generic import ListView
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.core.files import File
from django.http.response import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from core.utils import generate_price_history_charts
from core.models import PriceHistory, Target, Product, Category, Frequencies, SelectorTypes
from core.scraping.utils import run_explore_command
from core.tasks import scrape

class CategoryListView(LoginRequiredMixin, ListView):  # pylint: disable=too-many-ancestors
    ''' Class that provides the category list view '''

    template_name = 'core/categoryList.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.order_by('name').all()


class ProductListView(LoginRequiredMixin, ListView):  # pylint: disable=too-many-ancestors
    ''' Class that provides the product list view '''

    template_name = 'core/productList.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.order_by('name').all()


@login_required
def view_products_by_category(request, category_id):
    ''' Function that renders the products by category view '''

    products = Product.objects.filter(categories=category_id)

    return render(request, 'core/productList.html', {
        'products': products
    })


@login_required
@cache_page(21600, cache=("filesystem" if os.environ.get("ENV") == "prod" else "default"))
def view_price_history(request, product_id):
    ''' Function that renders the price history view '''

    targets = Target.objects.filter(product_id=product_id)
    if not targets:
        return render(request, 'core/priceHistory.html')

    history = PriceHistory.objects.filter(
        target_id__in=[t.id for t in targets])
    if not history:
        return render(request, 'core/priceHistory.html')

    product_name = targets[0].product.name
    data_frame = pd.DataFrame([{
        'Alias': h.target.alias,
        'url': h.target.url,
        'Price': h.price,
        'Collection date': h.created_at,
    } for h in history])
    target_refs = json.loads(data_frame.filter(
        items=['url', 'Alias']).drop_duplicates().to_json(orient='records'))

    charts = generate_price_history_charts(data_frame, product_name)

    return render(request, 'core/priceHistory.html', {
        'product_name': product_name,
        'target_refs': target_refs,
        'charts': charts
    })


@login_required
def view_download_database(request):
    ''' Function that renders the download database view '''

    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('index'))

    db_path = settings.DATABASES['default']['NAME']
    do_download = request.GET.get('do_download', False)

    if do_download and db_path:
        with File(open(db_path, "rb")) as db_file:
            new_name = f"{datetime.now()}{db_path}"
            response = HttpResponse(
                db_file, content_type='application/x-sqlite3')
            response['Content-Disposition'] = f'attachment; filename={new_name}'
            response['Content-Length'] = db_file.size

        return response

    return render(request, 'core/databaseDownload.html', {
        'db_path': db_path
    })


@login_required
def view_scrape_command(request):
    ''' Function that renders the scrape command view '''

    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('index'))

    if request.method == 'POST':
        frequency = request.POST['frequency']
        targets = request.POST.getlist('targets')
        scrape.delay(frequency=frequency, ids=targets)

    return render(request, 'core/scrapeCommand.html', {
        'frequencies': Frequencies.choices,
        'targets': Target.objects.values('id', 'alias', 'url').all()
    })


@login_required
def view_explore_command(request):
    ''' Funtion that renders the explore command view '''

    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('index'))

    exploration_result = None
    targets = Target.objects.all()

    if request.method == 'POST':
        operation = request.POST['operation']

        if operation == "download-result":
            result_file = request.POST['result_file']

            with File(open(result_file, "rb")) as file:
                response = HttpResponse(file, content_type='text/html')
                response['Content-Disposition'] = f'attachment; filename={result_file}'
                response['Content-Length'] = file.size

            return response

        if operation == "explore-custom":
            url = request.POST['url']
            selector_type = request.POST['selector-type']
            selector = request.POST['selector']

            exploration_result = run_explore_command(
                url, selector_type, selector)

        if operation == "explore-known":
            target_id = int(request.POST["selected-target"])
            selected_target = targets.filter(id=target_id).get()

            if selected_target.selector:
                selector_type = selected_target.selector.selector_type
                selector = selected_target.selector.selector
            else:
                selector_type = selected_target.custom_selector_type
                selector = selected_target.custom_selector

            exploration_result = run_explore_command(
                selected_target.url, selector_type, selector)

    return render(request, 'core/exploreCommand.html', {
        'selector_types': SelectorTypes.choices,
        'exploration_result': exploration_result,
        'targets': targets
    })

core/templates/core/categoryList.html
{% extends 'base.html' %} {% block content %}
<main class="container">
  <h1>Category list</h1>
  {% if categories %}
  <ul>
    {% for category in categories %}
    <li>
      <a href="{% url 'core:productsByCategoryView' category.id %}"
        >{{ category.name }}</a
      >
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <h2>No categories found</h2>
  {% endif %}
</main>
{% endblock %}

core/templates/core/databaseDownload.html
{% extends 'base.html' %} {% block content %}
<main class="container">
  {% if not db_path %}
  <h1>Database file not found!</h1>
  {% else %}
  <a href="{% url 'core:downloadDatabase' %}?do_download=True" target="__blank">Download database file</a>
  {% endif %}
</main>
{% endblock %}

core/templates/core/exploreCommand.html
{% extends 'base.html' %} {% block content %}
<main class="container">
  <h1>Explore command</h1>
  <form action="{% url 'core:exploreCommand' %}" method="post">
    {% csrf_token %}
    <article>
      <header>Select exploration type</header>
      <div class="grid">
        <label for="custom-target">
          <input
            type="radio"
            id="custom-target"
            name="size"
            value="custom-target"
            checked
          />
          Custom target
        </label>
        <label for="known-target">
          <input
            type="radio"
            id="known-target"
            name="size"
            value="known-target"
          />
          Known target
        </label>
      </div>
    </article>

    <article id="custom-target-inputs">
      <header>Custom target</header>
      <label for="url">Target url</label>
      <input type="text" name="url" />
      <label for="selector-type">Selector type</label>
      <select name="selector-type">
        <option value="">---</option>
        {% for type in selector_types %}
        <option value="{{ type.0 }}">{{ type.1 }}</option>
        {% endfor %}
      </select>
      <label for="selector">Selector</label>
      <input type="text" name="selector" />
      <input type="hidden" name="operation" value="explore-custom" />
      <button type="submit">Explore</button>
    </article>

    <article id="known-target-inputs" style="display: none">
      <header>Known target</header>
      <select name="selected-target">
        {% for target in targets %}
        <option value="{{ target.id }}">
          {% firstof target.alias target.url %}
        </option>
        {% endfor %}
      </select>
      <input type="hidden" name="operation" value="explore-known" />
      <button type="submit">Explore</button>
    </article>
  </form>

  {% if exploration_result %}
  <article>
    {% if exploration_result.success %}
    <header>Success</header>
    <div class="grid bottom-padded">
      <span>Status: {{ exploration_result.status }}</span>
      <span>Price: {{ exploration_result.price }}</span>
    </div>
    <div class="grid bottom-padded">
      <span>Duration {{ exploration_result.duration }}</span>
      <span>Started {{ exploration_result.start_time }}</span>
      <span>Ended {{ exploration_result.end_time }}</span>
    </div>
    {% else %}
    <header>Failed</header>
    <span>Status: {{ exploration_result.status }}</span>
    <span>{{ exploration_result.message }}</span>
    <p>{{ exploration_result.error }}</p>
    {% endif %}
    <form action="{% url 'core:exploreCommand' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="operation" value="download-result" />
      <input
        type="hidden"
        name="result_file"
        value="{{ exploration_result.result_file }}"
      />
      <input type="submit" value="Download result" />
    </form>
  </article>
  {% endif %}
</main>

<script>
  function onSubmit(event) {
    event.target.setAttribute("aria-busy", "true");
  }

  function onRadioClick(event) {
    if (event.target.value === "known-target") {
      knownDiv.style.display = "block";
      customDiv.style.display = "none";
    }

    if (event.target.value === "custom-target") {
      knownDiv.style.display = "none";
      customDiv.style.display = "block";
    }
  }

  const customDiv = document.querySelector("#custom-target-inputs");
  const knownDiv = document.querySelector("#known-target-inputs");

  document.querySelectorAll("input[type='radio']").forEach((radio) => {
    radio.onclick = onRadioClick;
  });

  document.querySelectorAll("button[type='submit']").forEach((btn) => {
    btn.onclick = onSubmit;
  });
</script>
{% endblock %}

core/templates/core/priceHistory.html
{% extends 'base.html' %} {% block content %}
<main class="container">
  {% if target_refs %}
  <h3>{{ product_name }}</h3>
  {% autoescape off %} {{ charts.line_chart }} {{ charts.scatter_plot }} {% endautoescape %}
  <br />
  <details>
    <summary>Go to product page</summary>
    <ul>
      {% for ref in target_refs %}
      <li>
        <a href="{{ ref.url }}" target="__blank">
          {% firstof ref.Alias ref.url %}
        </a>
      </li>
      {% endfor %}
    </ul>
  </details>
  {% else %}
  <h3>No price history found for this product</h3>
  {% endif %}
</main>
{% endblock %}

core/templates/core/productList.html
{% extends 'base.html' %} {% block content %}
<main class="container">
  {% if not products %}
  <h1>No products found for this category :(</h1>
  {% else %}
  <h1>Product list</h1>
  <ul>
    {% for product in products %}
    <li>
      <a href="{% url 'core:priceHistory' product.id %}"
        >{{ product.name }}</a
      >
    </li>
    {% endfor %}
  </ul>
  {% endif %}
</main>
{% endblock %}

core/templates/core/scrapeCommand.html
{% extends 'base.html' %} {% block content %}
<main class="container">
  <h1>Scrape command</h1>
  <article>
    <header>Scrape settings</header>
    <form action="{% url 'core:scrapeCommand' %}" method="post">
      {% csrf_token %}
      <label for="frequency">Frequencies</label>
      <select name="frequency" id="frequency">
        <option value="" select>---</option>
        {% for frequency in frequencies %}
        <option value="{{ frequency.0 }}">{{ frequency.1 }}</option>
        {% endfor %}
      </select>
      <label for="targets">Targets</label>
      <select name="targets" id="targets" multiple>
        {% for target in targets %}
        <option value="{{ target.id }}">
          {% firstof target.alias target.url %}
        </option>
        {% endfor %}
      </select>
      <button type="submit">Scrape</button>
    </form>
  </article>
  <!-- {% if running_commands %}
  <article>
    <header>Running commands</header>
    <ul>
      {% for command in running_commands %}
      <li>{{ command }}</li>
      {% endfor %}
    </ul>
  </article>
  {% endif %} -->
</main>

<script>
  function onSubmit(event) {
    event.target.setAttribute("aria-busy", "true");
  }

  document.querySelectorAll("button[type='submit']").forEach((btn) => {
    btn.onclick = onSubmit;
  });
</script>
{% endblock %}