core/urls.py
''' 
Module that provides all urls for core app.
'''

from django.urls import path
from core import views

app_name = 'core'
urlpatterns = [
    path('categories/', views.CategoryListView.as_view(), name='categoryList'),
    path('products/', views.ProductListView.as_view(), name='productList'),
    path('categories/<int:category_id>/',
         views.view_products_by_category, name='productsByCategoryView'),
    path('history/<int:product_id>/',
         views.view_price_history, name='priceHistory'),
    path('admin/db-download/', views.view_download_database,
         name="downloadDatabase"),
    path('admin/scrape', views.view_scrape_command, name="scrapeCommand"),
    path('admin/explore', views.view_explore_command, name="exploreCommand")
]

prihud/urls.py
import os
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('', views.Index, name='index'),
    path('login/', views.LoginView, name="login"),
    path('logout/', views.Logout, name="logout")
]

if (os.environ.get("ENV") == "dev"):
    urlpatterns += staticfiles_urlpatterns()

core/models.py
""" Module providing all models for the core app """

from django.utils.timezone import now
from django.db import models
from django.db.models import Min, Max
from django.utils.translation import gettext_lazy as _
from selenium.webdriver.common.by import By


class Statuses(models.TextChoices):
    """Choices for status field inside Target model"""

    SUCCESS = "S", _("Success")
    OUT_OF_STOCK = "O", _("Out of stock")
    NO_SELECTOR = "N", _("No selector set")
    PRICE_NOT_FOUND = "P", _("Price not found")
    CACHED = "C", _("Cached")
    UNDEFINED = "U", _("Undefined status")


class Frequencies(models.TextChoices):
    """Choices for frequency field inside Target model"""

    FOUR_TIMES = "F", _("Four times a day")
    TWO_TIMES = "T", _("Twice a day")
    DAILY = "D", _("Daily")
    WEEKLY = "W", _("Weekly")


class SelectorTypes(models.TextChoices):
    """Choices for custom_selector_type field inside Target model
    and selector_type field inside DefaultSelector model"""

    CSS = By.CSS_SELECTOR
    XPATH = By.XPATH
    TAG = By.TAG_NAME
    CLASS = By.CLASS_NAME


class Category(models.Model):
    """Category model"""

    name = models.CharField(max_length=128)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return self.name


class Product(models.Model):
    """Product model"""

    name = models.CharField(max_length=128)
    categories = models.ManyToManyField(Category)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return self.name

    def get_price_history(self):
        """Method for getting the price history of a product"""

        targets = Target.objects.filter(product_id=self.id).all()
        return (
            PriceHistory.objects.filter(target_id__in=[t.id for t in targets])
            .order_by("-created_at")
            .all()
        )

    def get_min_max_prices(self):
        """Method for getting the lowest and highest prices
        of a product's price history"""

        targets = Target.objects.filter(product_id=self.id).all()
        return PriceHistory.objects.filter(
            target_id__in=[t.id for t in targets]
        ).aggregate(Min("price"), Max("price"))

    def get_cheapest(self):
        """Get the cheapest price amongst all targets of a product"""

        targets = Target.objects.filter(product_id=self.id).all()
        return (
            PriceHistory.objects.filter(target_id__in=[t.id for t in targets])
            .annotate(Min("price"))
            .order_by("price")[0]
        )


class DefaultSelector(models.Model):
    """DefaultSelector model"""

    name = models.CharField(max_length=64)
    selector_type = models.CharField(max_length=16, choices=SelectorTypes.choices)
    selector = models.CharField(max_length=256)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return self.name


class Target(models.Model):
    """Target model"""

    alias = models.CharField(max_length=128, blank=True, null=True)
    url = models.CharField(max_length=256)
    selector = models.ForeignKey(
        DefaultSelector, on_delete=models.DO_NOTHING, blank=True, null=True
    )
    custom_selector_type = models.CharField(
        max_length=16, choices=SelectorTypes.choices, blank=True, null=True
    )
    custom_selector = models.CharField(max_length=256, blank=True, null=True)
    status = models.CharField(
        max_length=1,
        blank=True,
        null=True,
        choices=Statuses.choices,
        default=Statuses.SUCCESS,
    )
    frequency = models.CharField(
        max_length=1, choices=Frequencies.choices, default=Frequencies.DAILY
    )
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return self.alias or self.url

    def min_max_price(self):
        """Get the lowest and highest price of a target"""

        return PriceHistory.objects.filter(target_id=self.id).aggregate(
            Min("price"), Max("price")
        )

    def get_store_name_from_url(self):
        """Get store name from target url"""

        splitted = self.url.split(".")
        return splitted[1] if len(splitted) > 1 else ""

    def get_recent_price_history(self):
        """Get the most recent price history entry for a target"""

        return (
            PriceHistory.objects.filter(target_id=self.id)
            .order_by("-created_at")
            .first()
        )

    def is_available(self):
        """Check if a target is still available for purchase or not"""

        return self.status in [Statuses.SUCCESS, Statuses.CACHED]


class PriceHistory(models.Model):
    """PriceHistory model"""

    price = models.FloatField()
    target = models.ForeignKey(Target, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return f"{self.price} - {self.target} - {self.created_at}"


class Cookie(models.Model):
    """Cookie model"""

    url = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    value = models.TextField()
    path = models.CharField(max_length=256, null=True, default="/")
    domain = models.CharField(max_length=256)
    created_at = models.DateTimeField("created_at", default=now)
    updated_at = models.DateTimeField("updated_at", default=now)

    def __str__(self):
        return f"{self.url} - {self.name}"

    def get_all_grouped():  # pylint: disable=no-method-argument
        """Gets all cookies grouped by their url"""

        cookies = Cookie.objects.all()
        grouped = {}
        for cookie in cookies:
            if cookie.url not in grouped:
                grouped[cookie.url] = []
            grouped[cookie.url].append(cookie)
        return grouped

    def get_parsed(self):
        """Parses the cookie entry into a dict"""

        return {
            "name": self.name,
            "value": self.value,
            "path": self.path,
            "domain": self.domain,
        }

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Prihud{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'global.css' %}" />
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>
  </head>
  <body>
    <nav class="container">
      {% if user.is_authenticated %}
      <ul>
        <li
          class="clickable"
          onclick="window.location.assign('{% url 'index' %}')"
        >
          <strong class="center-aligned">
            <svg class="icon">
              <use href="{% static 'feather-sprite.svg' %}#crosshair" />
            </svg>
            Prihud
          </strong>
        </li>
      </ul>
      <ul>
        <li><a href="{% url 'core:categoryList' %}">Categories</a></li>
        <li><a href="{% url 'core:productList' %}">Products</a></li>
        {% if user.is_superuser %}
        <li role="list" dir="rtl">
          <a href="#" aria-haspopup="listbox">Admin</a>
          <ul role="listbox">
            <li><a href="{% url 'admin:index' %}">Admin Panel</a></li>
            <li><a href="{% url 'core:scrapeCommand' %}">Scrape</a></li>
            <li><a href="{% url 'core:exploreCommand' %}">Explore</a></li>
            <li>
              <a href="{% url 'core:downloadDatabase' %}">DB download</a>
            </li>
          </ul>
        </li>
        {% endif %}
        <li>
          <a href="{% url 'logout' %}">
            <svg class="icon">
              <use href="{% static 'feather-sprite.svg' %}#log-out" />
            </svg>
          </a>
        </li>
      </ul>
      {% else %}
      <ul>
        <li>
          <strong class="center-aligned">
            <svg class="icon">
              <use href="{% static 'feather-sprite.svg' %}#crosshair" />
            </svg>
            Prihud
          </strong>
        </li>
      </ul>
      <ul>
        <li>
          <a href="{% url 'login' %}">
            <svg class="icon">
              <use href="{% static 'feather-sprite.svg' %}#log-in" />
            </svg>
          </a>
        </li>
      </ul>
      {% endif %}
    </nav>
    {% block content %}{% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %} {% block content %} {% load static %}
<main class="container">
  <h1>Welcome back, {{ user.username }}</h1>
  {% if latest %}
  <h2>Latest entries</h2>
  <table>
    <thead>
      <tr>
        <th scope="col">Product</th>
        <th scope="col">Last price</th>
        <th scope="col">Min price</th>
        <th scope="col">Max price</th>
        <th scope="col">Checked at</th>
      </tr>
    </thead>
    <tbody>
      {% for entry in latest %}
      <tr>
        <td>
          {{ entry.target.product.name }}
          <a href="{% url 'core:priceHistory' entry.target.product.id %}">
            <svg class="icon icon--size-small">
              <use href="{% static 'feather-sprite.svg' %}#link" />
            </svg>
          </a>
          <a
            href="{{ entry.target.product.get_cheapest.target.url }}"
            target="__blank"
          >
            <svg class="icon icon--size-small">
              <use href="{% static 'feather-sprite.svg' %}#external-link" />
            </svg>
          </a>
        </td>
        <td>{{ entry.price }}</td>
        <td>{{ entry.target.product.get_min_max_prices.price__min }}</td>
        <td>{{ entry.target.product.get_min_max_prices.price__max }}</td>
        <td>{{ entry.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %} {% if inactive %}
  <h2>Recent abnormal targets</h2>
  <table>
    <thead>
      <tr>
        <th scope="col">Product</th>
        <th scope="col">Store name</th>
        <th scope="col">Status</th>
        <th scope="col">Checked at</th>
      </tr>
    </thead>
    <tbody>
      {% for entry in inactive %}
      <tr>
        <td>
          {{ entry.product.name }}
          <a href="{% url 'core:priceHistory' entry.product.id %}">
            <svg class="icon icon--size-small">
              <use href="{% static 'feather-sprite.svg' %}#link" />
            </svg>
          </a>
          <a href="{{ entry.url }}" target="__blank">
            <svg class="icon icon--size-small">
              <use href="{% static 'feather-sprite.svg' %}#external-link" />
            </svg>
          </a>
        </td>
        <td>{{ entry.get_store_name_from_url }}</td>
        <td>{{ entry.get_status_display }}</td>
        <td>{{ entry.get_recent_price_history.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
</main>
{% endblock %}

templates/login.html
{% extends 'base.html' %} {% block content %} {% load static %}
<main class="container">
  <article>
    <header>Login to Prihud</header>
    <form action="{% url 'login' %}" method="post">
      {% csrf_token %}
      <label for="username">
        Username
        <input type="text" name="username" id="username" required />
      </label>
      <label for="password">
        Password
        <input type="password" name="password" id="password" required />
      </label>
      <input type="submit" value="Login" />
    </form>
  </article>
  {% if login_failed %}
  <dialog open>
    <article>
      <header>
        <a href="" aria-label="Close" class="close" onclick="closeModal()"></a>
        <div class="center-aligned">
          <svg class="icon icon--size-large warn">
            <use href="{% static 'feather-sprite.svg' %}#alert-circle" />
          </svg>
          Error
        </div>
      </header>
      <span>Error trying to log in, please try again later</span>
    </article>
  </dialog>
  {% endif %}
</main>

{% if login_failed %}
<script>
  const closeModal = () =>
    document.querySelector("dialog").setAttribute("open", false);
</script>
{% endif %} {% endblock %}